apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: performance-topic-test
  labels:
    strimzi.io/cluster: kafka-cluster
  namespace: kafka
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1000000000
  partitions: 240
  replicas: 3
  topicName: performanceTopicTest