apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: $application-$test_name
spec:
  parallelism: 4
  script:
    configMap:
      name: $application-$test_name
      file: "integration-run.js" # <-- change here
  arguments: -o experimental-prometheus-rw --tag testid=$application-$test_name
  runner:
    metadata:
      labels:
        test-name: $application-$test_name
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/write
      - name: APP_URL
        value: $app_url
    serviceAccountName: k6-runner
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
      runAsNonRoot: true
  starter:
    metadata:
      labels:
        test-name: $application-$test_name
    serviceAccountName: k6-runner
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
      runAsNonRoot: true
